apiVersion: v1
data:
    MONGO_INITDB_ROOT_USERNAME: leonardo
    MONGO_INITDB_ROOT_PASSWORD: test
    MONGO_INITDB_DATABASE: fakedata
    MONGO_DB: fakedata
    MONGO_FAKE_COLLECTION: fakedatas
    MONGO_HOSTNAME: mongo-db-srv
    MONGO_PASSWORD: test
    MONGO_PORT: '27017'
    MONGO_USERNAME: leonardo
    PUBLIC_URL: http://rnmn.dev/
    KD_URL: https://kd.dev/#/login
kind: ConfigMap
metadata:
    name: env
---
apiVersion: v1
data:
    init.js: |
        db = new Mongo().getDB('fakedata');

        db.createCollection('fakedatas', { capped: false });

        db.fakedatas.insert([
        {
            username: 'leonardo',
            password: '12345',
            country: 'Venezuela',
            age: '25',
            role: 'Technical Leader | Full Stack Developer',
            hobby: 'Bicicle, Run, Volley, Soccer',
        },
        {
            username: 'pepe',
            password: '67890',
            country: 'United States',
            age: '18',
            role: 'Full Stack Developer',
            hobby: 'Run, GYM, Football',
        },
        {
            username: 'John',
            password: '67890',
            country: 'United States',
            age: '33',
            role: 'Killer',
            hobby: 'Sing, GYM, Racing',
        },
        {
            username: 'Wick',
            password: '67890',
            country: 'United States',
            age: '40',
            role: 'Scrum Master',
            hobby: 'Football',
        },
        ]);

kind: ConfigMap
metadata:
    creationTimestamp: null
    name: mongo-initdb
