apiVersion: v1
data:
    MONGO_INITDB_ROOT_USERNAME: leonardo
    MONGO_INITDB_ROOT_PASSWORD: test
    MONGO_INITDB_DATABASE: fakedata
    MONGO_DB: fakedata
    MONGO_FAKE_COLLECTION: fakedatas
    MONGO_HOSTNAME: mongo-db-srv
    MONGO_PASSWORD: test
    MONGO_PORT: '27017'
    MONGO_USERNAME: leonardo
    PUBLIC_URL: http://rnmn.dev/
kind: ConfigMap
metadata:
    name: env
---
apiVersion: v1
data:
    init.js: |
        db = new Mongo().getDB('fakedata');

        db.createCollection('fakedatas', { capped: false });

        db.fakedatas.insert([
            { username: 'leonardo', password: '12345' },
            { username: 'pepe', password: '67890' },
        ]);
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: mongo-initdb
